//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BL
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using OrdersAndisheh.DL;

	public class ItemSefaresh
	{
		public virtual OrderDetail OrderDetail
		{
			get;
			set;
		}

		public virtual Product Product
		{
			get;
			set;
		}

		public virtual Driver Driver
		{
			get;
			set;
		}

		public virtual Customer Customer
		{
			get;
			set;
		}

		public virtual int Tedad
		{
			get;
			set;
		}

		public virtual int TahvilFrosh
		{
			get;
			set;
		}

		public virtual bool HasOracle
		{
			get;
			set;
		}

		public virtual ItemType ItemKind
		{
			get;
			set;
		}

	}
}

