//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BL
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class SefareshService
	{
		public virtual Sefaresh Sefareshs
		{
			get;
			set;
		}

		public virtual void SaveSefaresh()
		{
			throw new System.NotImplementedException();
		}

		public virtual void UpdateSefaresh()
		{
			throw new System.NotImplementedException();
		}

		public virtual void AcceptSefaresh()
		{
			throw new System.NotImplementedException();
		}

		public virtual void UnAcceptSefaresh()
		{
			throw new System.NotImplementedException();
		}

		private void PrintReports()
		{
			throw new System.NotImplementedException();
		}

	}
}

