//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BL
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using OrdersAndisheh.DL;

	public class Sefaresh
	{
        public Sefaresh()
        {
            Items = new List<ItemSefaresh>();
            Order = new Order();
            AgarShodItems = new List<ItemSefaresh>();
            UsualItems = new List<ItemSefaresh>();
            ForiItems = new List<ItemSefaresh>();
            GovahiItems = new List<ItemSefaresh>();
        }

        private string tarikh = "";
		public string Tarikh
		{
            get { return tarikh ;}
            set
            {
                DateTime j;
                if (!DateTime.TryParse(value,out j))
                {
                    throw new ApplicationException("فرمت تاریخ وارد شده صحیح نمی باشد !");
                };
                tarikh = value;
            }
		}

		public string Description
		{
			get;
			set;
		}

        public Order Order
        {
            get;
            private set;
        }

       
        private List<ItemSefaresh> items;
        

	    public List<ItemSefaresh> Items
	    {
		    get { return items;}
		    set { 
                items = value;
                foreach (var item in items)
                {
                    switch (item.ItemKind)
                    {
                        case ItemType.Fori:
                            ForiItems.Add(item);
                            break;
                        case ItemType.Govahi:
                            GovahiItems.Add(item);
                            break;
                        case ItemType.AgharAmadeShod:
                            AgarShodItems.Add(item);
                            break;
                        case ItemType.Usual:
                            UsualItems.Add(item);
                            break;
                        default:
                            break;
                    }
                }
            }
	    }
	


		public virtual List<ItemSefaresh> AgarShodItems
		{
			get;
            private set;
		}

        public virtual List<ItemSefaresh> ForiItems 
		{
			get;
            private set;
		}

        public virtual List<ItemSefaresh> GovahiItems 
		{
			get;
            private set;
		}

        public virtual List<ItemSefaresh> UsualItems 
		{
			get;
            private set;
		}


        
    }
}

