//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersAndisheh.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public Driver()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public int Id { get; set; }
        public string Nam { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Pelak { get; set; }
        public string Car { get; set; }
        public Nullable<byte> Ton { get; set; }
        public Nullable<byte> Tol { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}
