//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersAndisheh.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public Nullable<int> Tedad { get; set; }
        public Nullable<int> TahvilForosh { get; set; }
        public string Description { get; set; }
        public short ProductId { get; set; }
        public short CustomerId { get; set; }
        public int DriverId { get; set; }
        public int OrderId { get; set; }
        public bool HasOracle { get; set; }
        public byte ItemType { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
