//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersAndisheh.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public short Id { get; set; }
        public string Code { get; set; }
        public string Nam { get; set; }
        public Nullable<double> Weight { get; set; }
        public string FaniCode { get; set; }
        public string CodeJense { get; set; }
        public Nullable<short> TedadDarPallet { get; set; }
        public Nullable<short> TedadDarSabad { get; set; }
        public byte PalletId { get; set; }
        public byte Bazres_Id { get; set; }
    
        public virtual Bazres Bazres { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual Pallet Pallet { get; set; }
    }
}
