//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BL
{
    using Stimulsoft.Report;
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System.Text;
    using System.Windows.Forms;

	public class FileManagar
	{
        
        private List<ReportRow> ReportRows;
        private string Tarikh;
        //private ObservableCollection<ItemSefaresh> items;
        

        public FileManagar(List<ReportRow> reportRows,string Tarikh )
        {
            this.ReportRows = reportRows;
            this.Tarikh = Tarikh;
        }

        //public FileManagar(ObservableCollection<ItemSefaresh> observableCollection)
        //{
        //    // TODO: Complete member initialization
        //    this.items = observableCollection;
        //}


        public void CreatDriverFile(string fileName)
        {
            string path = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
            using (FolderBrowserDialog dlg = new FolderBrowserDialog())
            {
                dlg.Description = "Select a folder";
                if (dlg.ShowDialog() == DialogResult.OK)
                {
                    path = dlg.SelectedPath;
                    if (string.IsNullOrEmpty(fileName))
                    {
                        fileName = "Report";
                    }
                    
                    StiReport mainreport = new StiReport();
                    mainreport.RegBusinessObject("Items", ReportRows);
                    mainreport.Load(AppDomain.CurrentDomain.BaseDirectory + "\\Report\\DriverListReport.mrt");
                    mainreport.Render();
                    mainreport.Show();
                    mainreport.ExportDocument(StiExportFormat.Pdf, path + "\\" + fileName + ".pdf");
                }
            }
        }
        
		public void CreatFile(string fileName)
		{
            string path = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
            using (FolderBrowserDialog dlg = new FolderBrowserDialog())
            {
                dlg.Description = "Select a folder";
                if (dlg.ShowDialog() == DialogResult.OK)
                {
                    //MessageBox.Show("You selected: " + dlg.SelectedPath);
                    path = dlg.SelectedPath;
                    if (string.IsNullOrEmpty(fileName))
                    {
                        fileName = "Report";
                    }
                    var h = new Header();
                    h.Tarikh = Tarikh;
                    h.WeekDay = PersianDateTime.Parse(Tarikh).DayName;



                    StiReport mainreport = new StiReport();
                    mainreport.RegBusinessObject("Sefaresh", h);
                    mainreport.RegBusinessObject("Items", ReportRows);
                    mainreport.Load(AppDomain.CurrentDomain.BaseDirectory + "\\Report\\Report.mrt");
                    mainreport.Render();
                    mainreport.Show();
                    mainreport.ExportDocument(StiExportFormat.Pdf, path + "\\" + fileName + ".pdf");
                }
            }
            
		}

        public virtual void CreatDocFile(string fileName)
        {
            string path = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
            using (FolderBrowserDialog dlg = new FolderBrowserDialog())
            {
                dlg.Description = "Select a folder";
                if (dlg.ShowDialog() == DialogResult.OK)
                {
                    //MessageBox.Show("You selected: " + dlg.SelectedPath);
                    path = dlg.SelectedPath;
                    if (string.IsNullOrEmpty(fileName))
                    {
                        fileName = "Report";
                    }
                    var h = new Header();
                    h.Tarikh = Tarikh;
                    h.WeekDay = PersianDateTime.Parse(Tarikh).DayName;



                    StiReport mainreport = new StiReport();
                    mainreport.RegBusinessObject("Sefaresh", h);
                    mainreport.RegBusinessObject("Items", ReportRows);
                    mainreport.Load(AppDomain.CurrentDomain.BaseDirectory + "\\Report\\Report.mrt");
                    mainreport.Render();
                    mainreport.Show();
                    mainreport.ExportDocument(StiExportFormat.RtfWinWord, path + "\\" + fileName + ".doc");
                }
            }
            
        }
        
        
    }
    public class Header
    {
        public string Tarikh { get; set; }
        public string WeekDay { get; set; }
    }
}

