//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BL
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using OrdersAndisheh.DBL;
    using System.ComponentModel;

    public class ItemSefaresh : INotifyPropertyChanged
	{
        public ItemSefaresh(Product p)
        {
            if (p==null)
            {
                throw new ApplicationException("کالا وجود ندارد !"); 
            }
            if (p.Code==null&p.Nam==null)
            {
                throw new ApplicationException("نام کالا یا کد کالا مشخص نمی باشد !"); 
            }
            OrderDetail = new OrderDetail();
            Product = p;
            HasOracle = true;
            ItemKind = ItemType.Usual;
        }

        public ItemSefaresh(OrderDetail od):this(od.Product)
        {
            if (od==null)
            {
                throw new ApplicationException("آیتم سفارش از دیتابیس وجود ندارد !");
            }
            
            this.OrderDetail = od;
        }

        public string Ranande
        {
            get { return (Driver==null?"":Driver.Nam); }
        }

        public string Maghsad
        {
            get { return (Customer==null?"":Customer.Name); }
        }

        public string Kala
        {
            get { return Product.Nam; }
        }

        public string BazresName
        {
            get 
            {
                if (Product.Bazre==null)
                {
                    throw new ApplicationException("باید بازرس های کالا ها از دیتابیس لود شود");
                }
                return Product.Bazre.Name; 
            }
        }

        public string CodeKala
        {
            get { return Product.Code; }
        }

       
		public OrderDetail OrderDetail
		{
			get;
			set;
		}

		public Product Product
		{
            private get { return OrderDetail.Product; }
            set { OrderDetail.Product = value;
            NotifyPropertyChanged("Kala");
            NotifyPropertyChanged("CodeKala");
            }
		}

		public Driver Driver
		{
            get { return OrderDetail.Driver; }
            set { OrderDetail.Driver = value;
            NotifyPropertyChanged("Ranande");
            }
		}

		public Customer Customer
		{
            get { return OrderDetail.Customer; }
            set 
            { 
                OrderDetail.Customer = value;
                NotifyPropertyChanged("Maghsad");
            }
		}
        public bool IsSelected { get; set; }
        //{
        //    get { return OrderDetail.Tedad; }
        //    set { OrderDetail.Tedad = value; }
        //}

		public int Tedad
		{
            get { return OrderDetail.Tedad; }
            set { OrderDetail.Tedad = value; }
		}

		public int TahvilFrosh
		{
            get { return OrderDetail.TahvilForosh; }
            set { OrderDetail.TahvilForosh = value; }
		}

		public bool HasOracle
		{
            get { return OrderDetail.HasOracle; }
            set { OrderDetail.HasOracle = value; }
		}

		public ItemType ItemKind
		{
            get { return (ItemType) OrderDetail.ItemType; }
            set { OrderDetail.ItemType = (byte) value; }
		}


        //TODO اینا رو باید محاسبه
        public int Karton { get; set; }

        public int Pallet { get; set; }

        public int Vazn { get; set; }

        public bool IsImenKala 
        {
            get { return Product.IsImenKala; }
            set { Product.IsImenKala = value; } 
        }

        public event PropertyChangedEventHandler PropertyChanged;

        private void NotifyPropertyChanged(String info)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(info));
            }
        }
    }
}

