//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BL
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ReportRow
	{
        public int Position { get; set; }
        public string Kala { get; set; }
        public string Tedad { get; set; }
        public string Karton { get; set; }
        public string Pallet { get; set; }
        public string Maghsad { get; set; }
        public string Vazn { get; set; }
        public string Ranande { get; set; }
    }
}

