//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BL
{
    using OrdersAndisheh.BL;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

	public class ReportRow : OrdersAndisheh.BL.IReportRow 
	{
        public int Position { get; set; }
        public string Kala { get; set; }
        public string Tedad { get; set; }
        public string Karton { get; set; }
        public string Pallet { get; set; }
        public string Maghsad { get; set; }
        public string Vazn { get; set; }
        public string Ranande { get; set; }
        public string Phone { get; set; }
        public string Car { get; set; }
        public string Pelak { get; set; }
        public bool IsKalaChanged { get; set; }
        public bool IsTedadChanged { get; set; }
        public bool IsCustomerChanged { get; set; }
        public bool IsDriverChanged { get; set; }


        public string TahvilFrosh { get; set; }
    }
}

