//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BL
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Reportd
	{
        private List<ItemSefaresh> sefareshat;
        

        public Reportd(string tarikh, List<ItemSefaresh> sefareshat)
        {
            this.sefareshat = sefareshat;
            this.Tarikh = tarikh;

            foreach (var item in sefareshat)
            {
                ListKala.Add(item.Kala);
                //List
            }
        }

        public string Tarikh { get; set; }
        //{
        //    get { return sefaresh.Tarikh; }
        //}

        //public string Description
        //{
        //    get { return sefaresh.Description; }
        //}

        public string RozHafte
        {
            get { return ""; } //برای محاسبه نام روز هفته - شنبه و یکشنبه
        }

        public List<string> ListKala { get; private set; }
        
    }
}

