//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BL
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ReportRow
	{
        public string kala;
        public string tedad;
        public string karton;
        public string pallet;
        public string maghsad;
        public string vazn;
        public string Ranande;

        public ReportRow(string kala, string tedad, string karton, string pallet, string maghsad, string vazn, string Ranande)
        {
            // TODO: Complete member initialization
            this.kala = kala;
            this.tedad = tedad;
            this.karton = karton;
            this.pallet = pallet;
            this.maghsad = maghsad;
            this.vazn = vazn;
            this.Ranande = Ranande;
        }
       

        //public ReportRow(string kala, int tedad, int karton, int pallet, string maghsad, int vazn, string Ranande)
        //{
            
        //}
        
        
    }
}

