//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BL
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Report
	{

        public string Tarikh { get; set; }

        private int myVar;

        public int Hafte
        {
            get { return myVar; }
            private set { myVar = value; }
        }
        
    }
}

