//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BL
{
	using OrdersAndisheh.DBL;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

	public class Sefaresh
	{
        public Sefaresh()
        {
            Items = new List<ItemSefaresh>();
            Order = new Order();
            AgarShodItems = new List<ItemSefaresh>();
            UsualItems = new List<ItemSefaresh>();
            ForiItems = new List<ItemSefaresh>();
            GovahiItems = new List<ItemSefaresh>();
        }

        public Sefaresh(Order order, List<OrderDetail> orderDetails):this()
        {
            if (orderDetails == null)
            {
                throw new ApplicationException("اطلاعات آیتم سفارش وجود ندارد");
            }
            this.Order = order;
            foreach (OrderDetail item in orderDetails)
            {
                Items.Add(new ItemSefaresh(item));
                //switch (item.ItemType)
                //{
                //    case 0:
                //        ForiItems.Add(new ItemSefaresh(item));
                //        break;
                //    case 1:
                //        GovahiItems.Add(new ItemSefaresh(item));
                //        break;
                //    case 2:
                //        AgarShodItems.Add(new ItemSefaresh(item));
                //        break;
                //    case 3:
                //        UsualItems.Add(new ItemSefaresh(item));
                //        break;
                //}
            }
        }

        
		public string Tarikh
		{
            get { return Order.Tarikh ;}
            set
            {
                DateTime j;
                if (!DateTime.TryParse(value,out j))
                {
                    throw new ApplicationException("فرمت تاریخ وارد شده صحیح نمی باشد !");
                };
                Order.Tarikh = value;
            }
		}

		public string Description
		{
			get { return Order.Description; }
            set { Order.Description = value; }
        }
		
        public Order Order
        {
            get;
            private set;
        }

       
        private List<ItemSefaresh> items;
        

	    public List<ItemSefaresh> Items
	    {
		    get { return items;}
		    set { 
                items = value;
                foreach (var s in value)
                {
                    Order.OrderDetails.Add(s.OrderDetail);
                }
                //foreach (var item in items)
                //{
                //    switch (item.ItemKind)
                //    {
                //        case ItemType.Fori:
                //            ForiItems.Add(item);
                //            break;
                //        case ItemType.Govahi:
                //            GovahiItems.Add(item);
                //            break;
                //        case ItemType.AgharAmadeShod:
                //            AgarShodItems.Add(item);
                //            break;
                //        case ItemType.Usual:
                //            UsualItems.Add(item);
                //            break;
                //        default:
                //            break;
                //    }
                //}
            }
	    }

        

		public virtual List<ItemSefaresh> AgarShodItems
		{
			get;
            private set;
		}

        public virtual List<ItemSefaresh> ForiItems 
		{
			get;
            private set;
		}

        public virtual List<ItemSefaresh> GovahiItems 
		{
			get;
            private set;
		}

        public virtual List<ItemSefaresh> UsualItems 
		{
			get;
            private set;
		}




        public bool Accepted 
        {
            get { return Order.Accepted; }
            set { Order.Accepted = value; } 
        }
    }
}

