//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BL
{

    public enum TahvilState : byte
	{
		OK,
		NoSefareshItem,
		TedadError,
		MaghsadErros,
	}
}
